#!/bin/bash                                                                                                                                                                                                                                                                   
#SBATCH -N 1                                                                                                                                                                                                                                                                  
#SBATCH -p LM                                                                                                                                                                                                                                                                 
#SBATCH --mem=1500G                                                                                                                                                                                                                                                           
#SBATCH -t 336:00:00                                                                                                                                                                                                                                                          
#SBATCH --workdir="/pylon2/mc3bg6p/al2025/isoform/SUPPA/"                                                                                                                                                                                                                     
#SBATCH --mail-user=al2025@wildcats.uhn.edu                                                                                                                                                                                                                                   
#SBATCH --mail-type=ALL                                                                                                                                                                                                                                                       
#echo commands to stdout                                                                                                                                                                                                                                                      

SALMON_DIR=/pylon2/mc3bg6p/al2025/storage/salmon-0.8.2/bin/
DATA=colLiv-v2_trans
SALMON_INDEX=/pylon2/mc3bg6p/al2025/isoform/SUPPA/${DATA}_index
PIGEON_ASSEMBLY=/pylon2/mc3bg6p/al2025/isoform/colLiv2_genome/Rockdove_cliv2.nuc.fasta
READ_LOC=/pylon2/mc3bg6p/al2025/parental_study/trim_cor_reads

cd /pylon2/mc3bg6p/al2025/isoform/SUPPA/

$SALMON_DIR/salmon index --type quasi --threads 28 --index ${DATA}_index -t $PIGEON_ASSEMBLY

SALMON_OUT=${DATA}_salmon_mapping
mkdir ${SALMON_OUT}


for i in $(ls $READ_LOC/*TRIM*R1.fq.gz); do

        SAMPLE=$(basename $i | sed 's/.TRIM.*R1.fq.gz//')
        OUTFILE_SALMON=${SAMPLE}_v1_maps.txt
        mkdir ${SALMON_OUT}/salmon_${SAMPLE}_v2

        $SALMON_DIR/salmon quant -i $SALMON_INDEX -l A \
        -1 $READ_LOC/$SAMPLE.TRIM*R1.fq.gz \
        -2 $READ_LOC/$SAMPLE.TRIM*R2.fq.gz \
        -p 32 --gcBias --seqBias --output ${SALMON_OUT}/salmon_${SAMPLE}_v2/${SAMPLE}_v2 2>&1 | tee -a $OUTFILE_SALMON
        echo ""

        cat $OUTFILE_SALMON >> ${DATA}_mapping_output.txt
        echo "" >> ${DATA}_mapping_output.txt
        rm $OUTFILE_SALMON
done

mv ${DATA}_mapping_output.txt $SALMON_OUT/
