#!/bin/bash
#SBATCH -N 1
#SBATCH -p LM
#SBATCH --mem=1500G
#SBATCH -t 8:00:00
#SBATCH --workdir="/pylon5/mc3bg6p/al2025/isoform/whippet_analysis/"
#SBATCH --mail-user=al2025@wildcats.uhn.edu
#SBATCH --mail-type=ALL
#echo commands to stdout

# Generates indices for desired genome. I generally have this in the job 
# submission file just preceeding the whippet-quant step

cd /pylon5/mc3bg6p/al2025/isoform/whippet_analysis/

julia /opt/packages/whippet/julia-0.6.0/v0.6/Whippet/bin/whippet-index.jl \
--fasta /pylon5/mc3bg6p/al2025/isoform/colLiv2_genome/GCA_001887795.1_colLiv2_genomic.fna \
--gtf /pylon5/mc3bg6p/al2025/isoform/colLiv2_genome/Rockdove_cliv2.convertedIDs.gtf \
--index /pylon5/mc3bg6p/al2025/isoform/whippet_analysis/index/ColLiv_v2
